name: Build Resourcepack

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Maak een zip van je resourcepack bestanden
      - name: Zip resourcepack
        run: zip -r resourcepack.zip assets pack.mcmeta pack.png

      # Bereken de SHA1 hash
      - name: Calculate SHA1
        id: sha1
        run: echo "sha1=$(sha1sum resourcepack.zip | awk '{print $1}')" >> $GITHUB_OUTPUT

      # Maak de output map voor GitHub Pages
      - name: Create output folder
        run: mkdir public

      # Verplaats de resourcepack.zip naar public/
      - name: Move resourcepack.zip
        run: mv resourcepack.zip public/

      # Maak pack-info.json
      - name: Create pack-info.json
        run: |
          echo '{
            "url": "https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/resourcepack.zip",
            "sha1": "${{ steps.sha1.outputs.sha1 }}"
          }' > public/pack-info.json

      # Deploy naar GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
