name: Build Resourcepack

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Zip resourcepack
        run: zip -r resourcepack.zip assets pack.mcmeta pack.png

      - name: Calculate SHA1
        id: sha1
        run: echo "sha1=$(sha1sum resourcepack.zip | awk '{print $1}')" >> $GITHUB_OUTPUT

      - name: Upload to GitHub Releases
        uses: softprops/action-gh-release@v1
        with:
          files: resourcepack.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Save info JSON
        run: |
          echo '{
            "url": "https://github.com/<user>/<repo>/releases/latest/download/resourcepack.zip",
            "sha1": "${{ steps.sha1.outputs.sha1 }}"
          }' > pack-info.json
